on:
 push :
  branches : main
name: 🚀 Prduction Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp://waws-prod-dm1-195.ftp.azurewebsites.windows.net/site/wwwroot/
        username: tazzer@ajay
        password: ${{ secrets.ftp_password }}